### PR TITLE
Add hint for autogenerated files

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

The `api.ts` file is autogenerated. This hides the file from diffs and excluded it from stats.

### CODE REVIEW

**Comment by thehabbos007** [comment]
Actually should we do this for more files in that directory?

**Review by thehabbos007 — CHANGES_REQUESTED** [review]
I believe we have more files in that directory which are also auto-generated. Let's add those as well

**Comment by TimDiekmann** [comment]
Thanks for the list, added those files 🙂

**Review by thehabbos007 — APPROVED** [review]
Thanks! sorry for the misguided approval at first :)

**Review by thehabbos007 — APPROVED** [review]
:

**Pull request merged**
