### PR TITLE
Add hiring banner to hash.dev

### PR DESCRIPTION
**Pull request by benwerner01**
## 🌟 What is the purpose of this PR?

Adds a simple hiring banner to the hash.dev site.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1200211978612931/1202154222315047/f) _(internal)_

## 🔍 What does this change?

- Adds hiring banner component from BP site

## ❓ How to test this?

1. Checkout the branch / view the deployment
1. Run `yarn install` for latest dependencies
2. Run `yarn workspace @hashintel/hashdev dev` do start the dev environment
3. Open `localhost:3000` in your browser, and checkout the hiring banner at the bottom.

## 📹 Demo

https://user-images.githubusercontent.com/42802102/167807094-7854fbca-cefa-477d-a2d8-8038d86bdad4.mov

### CODE REVIEW

**Comment by nonparibus** [comment]
@benwerner01 @nathggns Do we have Vercel deployment links for `hash.dev`?

**Comment by nathggns** [comment]
I don't know why the hashdev vercel check is "Canceled by Ignored Build Step" – it's possible it's because someone changed the path these files are in and maybe forgot to update that? I'm looking

**Comment by benwerner01** [comment]
@nathggns @nonparibus not sure if I'm missing something, but isn't this [the deployment right here](https://hashdev-1e8ay36cj-hashintel.vercel.app/)?

The latest deployment was cancelled I assume because I just merged `main` into the branch using "update branch", and I suppose vercel is smart enough to know that it shouldn't have affected the deployment.

**Comment by nathggns** [comment]
oh – my bad. Thanks Ben!

**Comment by MaggieAppleton** [comment]
I tweaked the colours ever so slightly, but overall this look great 👍

image

image

**Review by MaggieAppleton — APPROVED** [review]

**Review by nonparibus — APPROVED** [review]

**Pull request merged**
