### PR TITLE
Improve ranking of users in @ mention menu

### PR DESCRIPTION
**Pull request by teenoh**
## 🌟 What is the purpose of this PR?

~Currently the Mention Suggester (or @ menu) includes all users which isn't a desired behaviour. This PR updates it to only display members of an org if the user is in an org's workspace or just the user if the user is in their own workspace.~
This PR updates the Mention Suggester to display members of the active/current workspace first before other users.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/0/1202510248434796) _(internal)_

## ❓ How to test this?

1.  Checkout the branch
1.  Go to the org's workspace and confirm the org members show up first in the mention suggester (or @ menu)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202510248434796

### CODE REVIEW

**Comment by nonparibus** [comment]
I disagree with the rationale here, and I know Joseph had flagged he wasn't sure about intended behavior when he created the ticket.

All users _should_ be displayed, because we want absolutely any entity (which includes people) to be @ referenceable in HASH.

However users within an org _must_ be ranked above users from other orgs, as it is far more likely users will want to tag these.

Let's modify this PR.

**Review by nonparibus — CHANGES_REQUESTED** [review]
See above comment

**Comment by teenoh** [comment]
> I disagree with the rationale here, and I know Joseph had flagged he wasn't sure about intended behavior when he created the ticket.
> 
> All users _should_ be displayed, because we want absolutely any entity (which includes people) to be @ referenceable in HASH.
> 
> However users within an org _must_ be ranked above users from other orgs, as it is far more likely users will want to tag these.
> 
> Let's modify this PR.

Thanks for clarifying. Updated now

**Review by luisbettencourt — COMMENTED** [review]
Code looks good to me, but with this approach the list will always display users before pages, right? If so, is this intended?

**Comment by teenoh** [comment]
> Code looks good to me, but with this approach the list will always display users before pages, right? If so, is this intended?

Yes it is. The approach ensures "user" results and "page" results are grouped together while searching. That way it looks like this

```
user1
user2
page3
page4
```

Instead of 
```
user1
page3
page4
user2
```

**Review by luisbettencourt — APPROVED** [review]

**Review by kachkaev — APPROVED** [review]

**Pull request merged**
