### PR TITLE
Revert "CI: switch from quickinstall to `install-action`"

### PR DESCRIPTION
**Pull request by TimDiekmann**
This reverts https://github.com/hashintel/hash/pull/2021

## 🌟 What is the purpose of this PR?

We still encounter spurious failures in CI, which is especially annoying in merge queues. In the last days I had failures at least 4 times.

## 🔗 Related links

- https://github.com/hashintel/hash/pull/2021
- https://github.com/hashintel/hash/pull/2233: GH merge queue failed

### CODE REVIEW

**Review by indietyp — APPROVED** [review]
And I thought we were finally able to find a fix for it :/

**Comment by TimDiekmann** [comment]
Me, too, this is really sad 😞

**Comment by TimDiekmann** [comment]
I think the reason for the CI to fail is because of caching. I will look into it when the error happens again and put this PR in a draft state for the time being.

**Comment by TimDiekmann** [comment]
We only encountered this with `cargo-make` and we're going to replace `cargo-make` with `just`, so this PR is obsolete.

**Pull request closed without merging**
