### PR TITLE
H-14: Add RSS and Atom feeds to hash.dev/blog

### PR DESCRIPTION
**Pull request by CiaranMn**
## 🌟 What is the purpose of this PR?

- auto-generates RSS and Atom feeds for hash.dev/blog as part of building the blog index page
- adds discovery links to the blog index page
- removes a `Partial` that was wrapping the `Page` type (all posts have author, image etc, we don't need this)

### 🚢 Has this modified a publishable library?

This PR:

- [x] does not modify any publishable blocks or libraries, or modifications do not need publishing

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

- [x] do not affect the execution graph

## 🐾 Next steps

- We could add RSS & Atom icons to the blog homepage.

## ❓ How to test this?

1.  Once deployed, try `[PREVIEW_URL]/blog/feed.rss` and `[PREVIEW_URL]/blog/feed.atom` in [this validator](https://validator.w3.org/feed/) 
2. If you have a browser with RSS autodiscovery somehow (there's a Chrome extension) try visiting `/blog` and checking/running the autodiscovery feature/extension

## 📹 Demo

Screenshot 2023-07-05 at 16 41 37
Screenshot 2023-07-05 at 16 41 43

### CODE REVIEW

**Comment by nonparibus** [comment]
Can we add discovery links to all subpaths within `/blog`? i.e. the post pages as well (and in the future, if we ever have them, category pages)

Thank you!

**Review by benwerner01 — APPROVED** [review]
Thanks Ciaran, the code looks good to me and the RSS feed is working for me. I'm curious whether it's expected that some articles aren't displayed in the chrome extension? (e.g. "The non-negotiable principle")

**Comment by CiaranMn** [comment]
> Can we add discovery links to all subpaths within `/blog`? i.e. the post pages as well (and in the future, if we ever have them, category pages)
> 
> Thank you!

@nonparibus definitely – I've added the discovery links to every page, so people will see it when they land on the homepage or elsewhere too. There's no drawback to this I can think of. we can have discovery links for multiple feeds on the same page if we ever have them

**Review by nonparibus — APPROVED** [review]

**Comment by nonparibus** [comment]
Approved - thanks! Did you have any idea re: Ben's question/comment above?

**Comment by CiaranMn** [comment]
> Thanks Ciaran, the code looks good to me and the RSS feed is working for me. I'm curious whether it's expected that some articles aren't displayed in the chrome extension? (e.g. "The non-negotiable principle")

@benwerner01 it looks like the extension just takes the first 10 for its preview. The underlying RSS file includes all posts.

**Pull request merged**
