### PR TITLE
H-1735: Validate more custom data types

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

Add support for some more data type validations:
- `minimum`
- `maximum`
- `exclusiveMinimum`
- `exclusiveMaximum`
- `multipleOf`
- `format = "uri"`
- `format = "email"`

### CODE REVIEW

**Comment by nonparibus** [comment]
URI inc. URN, or just URLs? I was caught off-guard by the PR desc.

**Review by CiaranMn — APPROVED** [review]

**Comment by TimDiekmann** [comment]
> URI inc. URN, or just URLs? I was caught off-guard by the PR desc.

JSON Schema only allows `uri`: https://json-schema.org/draft/2020-12/json-schema-validation#name-uri-template

**Comment by nonparibus** [comment]
@TimDiekmann So `urn:isbn:9788184894677` would validate as correct for `URL`, even though it is a `URN`?

I think we want to capture `URN`s and `URL`s as separate **Data Types** (both of which would, in the future, exist within a single `URI` **Data Type Group**... assuming my mental map of how all these things inter-relate is correct).

**Comment by TimDiekmann** [comment]
Yes, it would. I also just tested your provided `URN` and it's passing. I agree that we probably want to support more than `URI` (especially as `URI` covers _a lot_), but this is supposed to be part of this PR as this would require to allow custom regexes. Properly validating URLs/URIs/URNs is an extremely ambitious goal.

**Comment by nonparibus** [comment]
Full validation is a lot of work. But basic checks can be done without it being "extremely ambitious", and must be done for us to move on to phase 2 CDTs.

My concern right now is that we want to call the data type, in the frontend, "URL" -- not URI. However, at present here, we accept URNs, not just URLs... so we must call it URI.

We can do that, and ship the thing we have now as "URI" in the user-facing app, because that is what it is. But while "good enough" for what we want right now, it is also not quite what we originally specced out here... and we should track the divergence. @TimDiekmann @CiaranMn

**Comment by TimDiekmann** [comment]
If we would add basic checks to check URLs ourselves we would match _way_ more than the check which are provided by the Rust crate. In addition I'm sure we would miss a lot of valid URLs and our validation would forbid them which results in super bad UX. What is the reason we cannot just use "URL" in the frontend? Every URL will be valid. But we cannot guarantee, that everything you throw at it will actually be a valid URL. Unless we find a URL validator which guarantees that we cannot provide that functionality.

**Pull request merged**
