### PR TITLE
H-3122: Make choosing relevant links quicker / more efficient

### PR DESCRIPTION
**Pull request by CiaranMn**
## 🌟 What is the purpose of this PR?

As part of research tasks, we have an agent which chooses which links to follow next. The input to this is a set of links which are potentially relevant to the research task. Previously, these links were chosen by feeding the HTML for the currenet page into Claude Sonnet and asking it to provide relevant links. This approach was disproportionately expensive for the simple task. This PR switches the 'relevant link choosing' agent to Claude Haiku, and provides it the extracted anchor tags with text from HTML rather than the entire HTML.

As part of this I ran the link chooser through the prompt optimizer and updated the system prompt.

### 🚢 Has this modified a publishable library?

This PR:

- [x] does not modify any publishable blocks or libraries, or modifications do not need publishing

### 📜 Does this require a change to the docs?

The changes in this PR:

- [x] are internal and do not require a docs change

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

- [x] do not affect the execution graph

## 🐾 Next steps

Next steps for Flow improvements:
- H-3127: Improve 'fact from text' resilience / reduce errors
- H-3128: add progress heartbeating for research coordinator (to resume from if the flow errors)

## 🛡 What tests cover this?

- None yet

## ❓ How to test this?

1. Run a flow

### CODE REVIEW

**Comment by vilkinsons** [comment]
@CiaranMn Can approve when linting fixed. Might be worth us resurrecting/using the old pre-commit hooks?

**Comment by CiaranMn** [comment]
> Can approve when linting fixed. 

Done

> Might be worth us resurrecting/using the old pre-commit hooks?

I have the pre-commit hooks on, they don't run `eslint`. We could add it. I did run `yarn lint` before pushing but must've missed the failure in the rest of the output.

**Comment by vilkinsons** [comment]
@CiaranMn Still failing :(

**Comment by CiaranMn** [comment]
> @CiaranMn Still failing :(

Boo - fixed now!

**Review by vilkinsons — APPROVED** [review]

**Pull request merged**
