### PR TITLE
Disable backend integration and playwright checks in `dev/graph`

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

Backend Integration tests and playwright tests are expected to failed, disable them to avoid  ❌  on every PR.

## 🎥 

image

### CODE REVIEW

**Comment by thehabbos007** [comment]
Just curious, but this would only disable the CI on the `dev/graph` branch itself, but not PRs opened against the branch, right? Do we want the CI skipping to also work on the PRs against the `dev/graph` branch?

**Comment by TimDiekmann** [comment]
> Just curious, but this would only disable the CI on the `dev/graph` branch itself, but not PRs opened against the branch, right? Do we want the CI skipping to also work on the PRs against the `dev/graph` branch?

Exactly, I already fixed this 🙂

**Review by benwerner01 — APPROVED** [review]
Thanks @TimDiekmann 🎉

**Comment by TimDiekmann** [comment]
Waiting for #714

**Pull request merged**
