### PR TITLE
[H-7] Update HASH developer site (`hash.dev`) content, layout and styles

### PR DESCRIPTION
**Pull request by benwerner01**
## 🌟 What is the purpose of this PR?

This PR updates the homepage and blog pages with new designs.

## 🔗 Related links

- [Implement homepage redesign on hash.dev](https://app.asana.com/0/1204727813960182/1204904958011586/f) _(internal)_
- [Implement blog post page tweaks on hash.dev](https://app.asana.com/0/1204727813960182/1204905115822402/f) _(internal)_

## 🔍 What does this change?

See commits.

### 🚢 Has this modified a publishable library?

This PR:

 - [x] does not modify any publishable blocks or libraries, or modifications do not need publishing

### 📜 Does this require a change to the docs?

The changes in this PR:

- [x] is internal and does not require a docs change

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

 - [x] does not affect the execution graph

## 🐾 Next steps

- add `/tutorials` pages
- add `/docs` pages
- add `/roadmap` page
- add search functionality to navbar and 404 page

## 🛡 What tests cover this?

None

## ❓ How to test this?

View the vercel deployment.

### CODE REVIEW

**Review by CiaranMn — COMMENTED** [review]
I've scanned the code and added one comment which may or may not need a change.

The spacing between paragraphs looks too big (as it is in prod) – it looks like the intention is to have this narrower (just dropping the 16px bottom margin gets it closer to the designs)

**Comment by benwerner01** [comment]
> The spacing between paragraphs looks too big (as it is in prod) – it looks like the intention is to have this smaller (just dropping the 16px bottom margin gets it closer to the designs)

I'm assuming you're referring to the paragraphs on the blog post pages, I've adjusted this in https://github.com/hashintel/hash/pull/2690/commits/5bb78211956091359267a867d57f72e1aaa0e76f. I've also slightly tweaked the spacing between list items in bulleted lists which seemed too large to me.

**Comment by nonparibus** [comment]
Looks good. Left a small number of minor comments (including one about a mobile styling issue on the homepage).

**Review by nonparibus — CHANGES_REQUESTED** [review]
Looks good. Left a small number of minor comments (including one about a mobile styling issue on the homepage). My comments are small enough that @CiaranMn I think this is generally ready for code review.

**Review by nonparibus — APPROVED** [review]
Good work!

**Pull request merged**
