### PR TITLE
Move `sites` to `apps`, rename included workspaces

### PR DESCRIPTION
**Pull request by kachkaev**
## 🌟 What is the purpose of this PR?

This PR moves `sites` to `apps` and renames folder mentions accordingly. Containing workspaces are renamed from `@hashintel/hashai` and `@hashintel/hashdev` to `@apps/hashdotai` and `@apps/hashdotdev`. The new `apps` folder will eventually contain more workspaces as we move some from `packages/hashintel`.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203271043333970/1203308051416190/f) _(internal)_

## 📜 Does this require a change to the docs?

- Docs in this repo are updated
- Docs in BP repo do not refer to `sites` folder in this repo

## ⚠️ Known issues

- Vercel deployment for `hashdev` is failing

## 🐾 Next steps

- Update Vercel config after receiving PR approval
- Merge https://github.com/hashintel/internal/pull/3421 (internal)

## 🛡 What tests cover this?

CI

### CODE REVIEW

**Comment by nonparibus** [comment]
@kachkaev The original _monorepo restructure_ meeting outcomes document refers to these folders at `hashdotai` and `hashdotdev` which I believe was a suggestion made in-meeting to allow for easier at-a-glance identification (and alphabetized sorting/clustering) of our _websites_ within this `/apps` folder. Can we make this change as part of this PR, or did you have concerns? @CiaranMn confirms he recalls similarly.

**Comment by kachkaev** [comment]
@nonparibus I was not planning to do anything but renaming `sites` to `apps` to keep this PR focused on the root folder contents. But your suggestion makes sense – now seems to be a good time to add `dot` too. That’s done, thanks for the idea!

In theory, we can even go for `@apps/hash.ai` and `@apps/hash.dev` because these are valid workspace and folder names. Happy to update the PR once again if you prefer `.` to `dot`.

**Comment by nonparibus** [comment]
@kachkaev I'd like to avoid dots in folder names (for the widest array of dumb file system support). I had also since quite subscribed to your idea of having workspace names match the repo directory structure, so am reticent to agree to any divergence here. Prior Alex from 2 weeks ago wins this argument!

**Comment by nonparibus** [comment]
To fix the deployment issue we simply need to change the `Root Directory` path on the Vercel [project page](https://vercel.com/hashintel/hashdev/settings/general).

Once the Vercel root dir path has been updated, a new deployment will be required for the change to take effect. We should therefore change the root dir immediately prior to re-triggering GH Actions and merging this PR.

**Review by CiaranMn — APPROVED** [review]

**Pull request merged**
