### PR TITLE
H-3207: Clean up package.json and sync script

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

The sync script generates wrong `private` flags for crates which are not set to `publish = false`. Also, it generates empty sections in `package.json`. In addition, a few package.jsons are missing.

### CODE REVIEW

**Comment by indietyp** [comment]
We might want to add `workspace.package.publish = false` into the root workspace as well.

one of the supported keys: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

**Comment by indietyp** [comment]
version is also supported, so we could inherit `version = "0.0.0"`, tho idk if that is a good idea.

**Comment by TimDiekmann** [comment]
I would add neither. Versions should be explicit and publish is just a boolean flag, I don't see a point of inheriting it.

**Review by CiaranMn — DISMISSED** [review]

**Comment by indietyp** [comment]
primarily for `cargo new` (that's how I generate packages), adding `publish` and `version` is the thing I usually forget.

also sorry for the recent publish mistakes D: it's so easy to forget adding the two keys to the manifest.

**Comment by TimDiekmann** [comment]
Oh, the `cargo new` fact is interesting. I think I _never_ used that command 😄

**Comment by vilkinsons** [comment]
We could consider doing this for `cargo new` ^ Happy to provide re-approval when we reach a decision on this.

**Comment by TimDiekmann** [comment]
Already did: [`1667f4c` (#4787)](https://github.com/hashintel/hash/pull/4787/commits/1667f4c1af547d1dc22e19ca13d5967ba5c5121f)

**Review by vilkinsons — DISMISSED** [review]

**Review by vilkinsons — APPROVED** [review]

**Pull request merged**
