### PR TITLE
Hide sitewide news banner on HASH.dev 

### PR DESCRIPTION
**Pull request by luisbettencourt**
## 🌟 What is the purpose of this PR?

This PR hides the site wide hiring banner on `hash.dev`

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203363157432087/1203583989086885/f) _(internal)_

### CODE REVIEW

**Review by kachkaev — COMMENTED** [review]
Can we also delete all code associated with it? It will remain in history and we'll be able to restore it with `git revert`. I’m not a fan of keeping files ‘just in case’ – they are source of clutter.

**Review by kachkaev — APPROVED** [review]

**Comment by nonparibus** [comment]
I disagree with Alex on this one, and I have made this case before.

Until this is in a design-system pkg please keep it around.

**Review by kachkaev — CHANGES_REQUESTED** [review]
linting 🙏


```
@apps/hashdotdev:lint:eslint: /home/runner/work/hash/hash/apps/hashdotdev/src/components/PageLayout.tsx
@apps/hashdotdev:lint:eslint:   5:10  error  'HiringBanner' is defined but never used. Allowed unused vars must match /^_+/u  @typescript-eslint/no-unused-vars
@apps/hashdotdev:lint:eslint:   5:30  error  Unable to resolve path to module './HiringBanner'                                import/no-unresolved
@apps/hashdotdev:lint:eslint:   5:30  error  Missing file extension for "./HiringBanner"                                      import/extensions
```

**Review by nonparibus — CHANGES_REQUESTED** [review]
See above.

**Review by nonparibus — APPROVED** [review]

**Review by kachkaev — APPROVED** [review]

**Pull request merged**
