### PR TITLE
Add labeler Action

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

Automatically applies labels for hEngine, HASH, stdlib and learn.

## 🔗 Related links

- [Asana task description](https://app.asana.com/0/1199550852792314/1201533886101111/f)

### CODE REVIEW

**Review by CiaranMn — COMMENTED** [review]
Thanks Tim - a couple of thought on this, on which I'd also welcome input from @nonparibus:

1. I like the Area / Category / Experience / Status split
2. I'm also happy with `engine` vs `hengine` (no confusion with `hen-gine`), but welcome David's views
3. I'm not sure about distinguishing `stdlib` from `engine`. Did we already have a `stdlib` label? I think now we have the whole engine in the repo, it might not make sense to distinguish the `stdlib` bit of it from the rest of it - at least, not until we have labels for other bits (e.g.  `datastore`, `language_runners`)

**Comment by nonparibus** [comment]
Ditto Ciaran's comments above. LGTM

**Comment by TimDiekmann** [comment]
>     3. I'm not sure about distinguishing `stdlib` from `engine`. Did we already have a `stdlib` label? I think now we have the whole engine in the repo, it might not make sense to distinguish the `stdlib` bit of it from the rest of it - at least, not until we have labels for other bits (e.g.  `datastore`, `language_runners`)

No, we didn't had `stdlib` before. Fair points, I'll remove it and we can rethink of it after [Better separation of crates](https://app.asana.com/0/1199550852792314/1201481007343142/f) has landed.

**Review by CiaranMn — APPROVED** [review]
Great stuff, thanks Tim!

**Pull request merged**
