### PR TITLE
Dev/integrations

### PR DESCRIPTION
**Pull request by colelawrence**
WIP branch opened to observe changes in progress.

Pairing with @Alfred-Mountfield

### CODE REVIEW

**Comment by colelawrence** [comment]
If this is planned to be squashed and merged, I strongly recommend keeping a separate branch in the repo so some of the individual commits can be referenced later for understanding.

**Comment by Alfred-Mountfield** [comment]
Closing this branch as the exploration here has resulted in a change in implementation direction.

**Comment by nonparibus** [comment]
@Alfred-Mountfield Can you x-link to the internal docs where we've mentioned this work here for posterity? Thanks. (Sad we can't say "closing the loop" in contexts where it would otherwise make sense anymore)

**Comment by Alfred-Mountfield** [comment]
> Can you x-link to the internal docs where we've mentioned this work here for posterity? Thanks. (Sad we can't say "closing the loop" in contexts where it would otherwise make sense anymore)

Sure thing, am in the middle of adding the links going the other way

**Pull request closed without merging**
