### PR TITLE
Implement custom cell for "Data Type" column on entity editor

### PR DESCRIPTION
**Pull request by yusufkinatas**
## 🌟 What is the purpose of this PR?

This PR applies the design to the cells of "Data Type" column

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1201095311341924/1203199644802781/f) _(internal)_
- [Design](https://www.figma.com/file/gydVGka9FjNEg9E2STwhi2/HASH-App?node-id=5381%3A248949) _(internal)_

## 🔍 What does this change?

- Create custom cell `data-type-cell`
- Make `draw-cell-fade-out-gradient` a generic utility function to provide fade out gradient to any custom cell

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Open entity editor
1.  Compare the "Data Type" columns design with Figma design.

## 📹 Demo

https://user-images.githubusercontent.com/39553853/197831390-55544fc0-b961-4afb-9e89-729f1e9c5add.mov

### CODE REVIEW

**Comment by nathggns** [comment]
Looking at the demo, I'm not certain the canvas chips match the shape of the HTML/JSX chips. Are my eyes playing tricks? @nonparibus

**Review by nathggns — APPROVED** [review]
Code is fine – just that comment about visuals to check on before merging.

**Comment by nonparibus** [comment]
> Looking at the demo, I'm not certain the canvas chips match the shape of the HTML/JSX chips. Are my eyes playing tricks? @nonparibus 

I can't tell the difference, but it's 3:44am 🫠

**Comment by yusufkinatas** [comment]
It's not %100 matching, because of Canvas API does not support `context.roundRect` yet, and the current `roundRect` solution looks just a little bit different than actual `border-width: 50%`. I think it's ok for now since the difference is only visible if users want to open the overlay for data-type cells. And it's pretty minor.

**Review by CiaranMn — APPROVED** [review]

**Pull request merged**
