### PR TITLE
Move local libs from `packages`

### PR DESCRIPTION
**Pull request by kachkaev**
## 🌟 What is the purpose of this PR?

This PR moves three local workspaces:

```
📂 packages/hash/backend-utils   → libs/@local/hash-backend-utils
📦 @hashintel/hash-backend-utils   @local/hash-backend-utils

📂 packages/hash/design-system   → libs/@local/design-system
📦 @hashintel/hash-design-system   @local/design-system

📂 packages/hash/shared          → libs/@local/hash-isomorphic-utils
📦 @hashintel/hash-shared          @local/hash-isomorphic-utils
```

It also adds `LICENSE.md` to `libs/@local/*` to improve CI results in #1825.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203543021352032/1203324923411371/f) _(internal)_

## ⚠️ Known issues

- Vercel deployment for Design System fails. I’ll fix this just before merging this PR by updating workspace path in Vercel UI.

## 🐾 Next steps

- Move remaining apps to `apps`

## 🛡 What tests cover this?

- CI

### CODE REVIEW

**Review by nonparibus — CHANGES_REQUESTED** [review]
@kachkaev Could you add the same `LICENSE.md` file to the [`design-system`](https://github.com/hashintel/hash/tree/ak/move-local-libs/libs/%40local/design-system) that you've added to the other `libs/@local` dirs here? Thanks.

**Comment by nonparibus** [comment]
Also to flag: the PR description refers to:
> 📂 packages/hash/design-system   → libs/@local/hash-design-system
> 📦 @hashintel/hash-design-system   @local/hash-design-system

...but the folder is just `design-system`, and I presume the Yarn workspace is, too?

**Comment by kachkaev** [comment]
@nonparibus I renamed `libs/@local/design-system` to `libs/@local/hash-design-system`. Thanks for spotting!

**Comment by nonparibus** [comment]
> @nonparibus I renamed `libs/@local/design-system` to `libs/@local/hash-design-system`. Thanks for spotting!

Do we think this is preferable to `design-system`? I would lean towards the shorter form option. Ideally the DS wouldn't be specific to our one product, but the entire brand (i.e. everything in this repo) making the name somewhat tautological and misleading if all other `hash-` prefixed things refer to the _app_ as opposed to _org-wide_ initiatives.

**Comment by nonparibus** [comment]
@kachkaev Additionally, the 3/4 changes in https://github.com/hashintel/hash/pull/1831/commits/ccc3b19e0e51b6e2bc2922a488bef86f93c2a02d conflict with that introduced in https://github.com/hashintel/hash/pull/1846, which IMO represents a more robust solution to the problem.

**Comment by kachkaev** [comment]
> Additionally, the 3/4 changes in https://github.com/hashintel/hash/pull/1831/commits/ccc3b19e0e51b6e2bc2922a488bef86f93c2a02d conflict with that introduced in https://github.com/hashintel/hash/pull/1846, which IMO represents a more robust solution to the problem.

This has been resolved in https://github.com/hashintel/hash/pull/1831/commits/6372c29b3fa51d8ec1423e3cfd72e98c9d954fcd

**Comment by kachkaev** [comment]
> Do we think this is preferable to `design-system`? I would lean towards the shorter form option. Ideally the DS wouldn't be specific to our one product, but the entire brand (i.e. everything in this repo) making the name somewhat tautological and misleading if all other `hash-` prefixed things refer to the _app_ as opposed to _org-wide_ initiatives.

I don’t have a strong preference either way. I renamed `@local/hash-design-system` to `@local/design-system` in https://github.com/hashintel/hash/pull/1831/commits/73ec9624ee35b67be398212c978c1c0156e0aea0.

**Comment by nonparibus** [comment]
Product ✅

Deferring to @CiaranMn on code changes.

**Review by nonparibus — CHANGES_REQUESTED** [review]
https://github.com/hashintel/hash/pull/1831#pullrequestreview-1249248808 still outstanding.

**Comment by kachkaev** [comment]
> https://github.com/hashintel/hash/pull/1831#pullrequestreview-1249248808 still outstanding.

Addressed in https://github.com/hashintel/hash/pull/1831/commits/88a1c9c61e9534ea34e803c0ed4332a81c9e2d0c

**Review by nonparibus — APPROVED** [review]
Looks good from my side (in terms of product). Haven't reviewed the code so please wait for someone on that. Thanks.

**Review by CiaranMn — APPROVED** [review]

**Review by CiaranMn — APPROVED** [review]

**Review by nonparibus — APPROVED** [review]

**Pull request merged**
