### PR TITLE
Update workflow name casing and LICENSE quick-ref guide

### PR DESCRIPTION
**Pull request by nonparibus**
## 🌟 What is the purpose of this PR?

- Renames `merging-enabled` workflow from "merging enabled" to "Merging enabled", for consistency with others
- Improves quick reference guide in the root LICENSE file

### CODE REVIEW

**Review by TimDiekmann — APPROVED** [review]
LGTM 🎉 

Please make sure to also update the Branch protection rules to match the new casing of `Merging enabled`.

**Comment by TimDiekmann** [comment]
Is there somewhere else I should be adjusting?

To my knowledge, that should be sufficient. If not, the worst that could happen is that this PR is not merged.

**Comment by TimDiekmann** [comment]
It seems you have to tweak the branch protection rules 🙂 
image

**Comment by nonparibus** [comment]
> It seems you have to tweak the branch protection rules image

I can't see how they can be tweaked. I think this just needs to merge, first.

**Comment by CiaranMn** [comment]
Updated required checks (it's in Branches -> Branch protection [rules](https://github.com/hashintel/hash/settings/branch_protection_rules/22430586))

**Pull request merged**
