### PR TITLE
Implement settings bar in the Table block

### PR DESCRIPTION
**Pull request by luisbettencourt**
## 🌟 What is the purpose of this PR?

This PR adds a settings bar to the Table block, to make it more consistent with other block (FAQ block, AI Image block, etc).

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203801045329780/1204298893311426/f) _(internal)_

## 🔍 What does this change?

- Added `Get Help` link;
- Moved settings that were previously in the settings menu to the settings bar;
- Collapsed bar for smaller screen sizes.

### 🚢 Has this modified a publishable library?

This PR:

- [x] modifies a **block** that will need publishing via GitHub action once merged 

### 📜 Does this require a change to the docs?

The changes in this PR:

 - [x] is internal and does not require a docs change

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

- [x] does not affect the execution graph 

## 📹 Demo

demo

### CODE REVIEW

**Comment by nonparibus** [comment]
@luisbettencourt Can we flip this on its head so that the labels read "Show header row" and "Show row numbers" instead of hide? So that when they are toggled 'on' these things are visible. I think it might be a bit easier to grok.

**Comment by nonparibus** [comment]
Thanks. Functionally the screen-recording/changes LGTM so over to @hashintel/frontend for a review.

**Comment by luisbettencourt** [comment]
@yusufkinatas raised concerns about the settings bar visibility in mobile. Currently, settings are shown by clicking on the header or by long pressing the table.

https://user-images.githubusercontent.com/37453800/236170328-348f6524-2af4-4626-9675-ff0c8f5c61cd.mp4

Are you happy with this or would you rather it always be shown in mobile @nonparibus ?

**Comment by nonparibus** [comment]
@luisbettencourt Let's make this omnipresent for now, on touch input devices, so always visible.

**Review by yusufkinatas — APPROVED** [review]
LGTM!

**Review by yusufkinatas — APPROVED** [review]

**Pull request merged**
