### PR TITLE
[H-41] Save less frequently

### PR DESCRIPTION
**Pull request by CiaranMn**
## 🌟 What is the purpose of this PR?

Closes https://github.com/hashintel/hash/pull/2606 in favour of cherry-picking the commit there Nate introduced to reduce save frequency.

### 🚢 Has this modified a publishable library?

This PR:

- [x] does not modify any publishable blocks or libraries, or modifications do not need publishing -->

### 📜 Does this require a change to the docs?

The changes in this PR:

- [x] are internal and do not require a docs change -->

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

- [x] do not affect the execution graph -->

## ❓ How to test this?

1.  Check that saving in a page still works

### CODE REVIEW

**Comment by nonparibus** [comment]
@TimDiekmann This appears to have deployed `hashdotdev` when it didn't need to, while not deploying `hash` (which it should have). Any idea why?

**Comment by TimDiekmann** [comment]
The first commit on a branch will always try to deploy (except `hcore-plugin-pm` which uses a different rule). Any further commit should ignore the deployment.

**Comment by TimDiekmann** [comment]
Investigated further: The first commit triggered a HASH deployment. The second was canceled because it didn't change the code to trigger another deployment. So everything's good 👍

**Review by benwerner01 — APPROVED** [review]
Thanks Ciaran, looks good to me and saving is working for me locally 👍

**Pull request merged**
