### PR TITLE
Add unique objectIDs to each markdown-rendered page

### PR DESCRIPTION
**Pull request by akash-joshi**
At HASH, we are currently indexing all of our MDX-rendered web pages under Algolia search, so that we can have a search bar present for all our articles in the [learning set of pages](https://hash.ai/docs/simulation).

To do that, we need to have a unique ID attached to each element so that they are automatically updated whenever we make a change to the page. So, this PR adds a `objectID` to each of these pages, which would primarily be used for Algolia indexing, but can be used for other purposes like analytics as well.

### CODE REVIEW

**Comment by nonparibus** [comment]
How are these generated? (E.g. if a user were to submit a new page to the docs, how would it obtain one of these objectIds?)

**Comment by CiaranMn** [comment]
Can we case it as `objectId`? It's how we are casing ids elsewhere

**Comment by akash-joshi** [comment]
@CiaranMn Algolia uses `objectID` so I used that: https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/how-to/incremental-updates/#updating-records

@nonparibus I've created one-time scripts to add the objectID for now, we can use GitHub Actions for repeated additions later.

**Comment by CiaranMn** [comment]
> @CiaranMn Algolia uses objectID so I used that

I'd rather we were consistent in our own codebase, and converted the field name when sending it to Algolia.

Can we give all the pages titles and slugs also please? Some are missing them.

**Comment by akash-joshi** [comment]
> I'd rather we were consistent in our own codebase, and converted the field name when sending it to Algolia.
> 
> Can we give all the pages titles and slugs also please? Some are missing them.

@CiaranMn fixed both things. The missing titles and slugs were because some of the pages weren't in the `url_maps`, so they weren't read.

**Review by CiaranMn — APPROVED** [review]

**Pull request merged**
