### PR TITLE
Blog post page (MDX)

### PR DESCRIPTION
**Pull request by nathggns**
## 🌟 What is the purpose of this PR?

A new blog post page implemented on MDX. 

### Todos

- [x] Social metadata / semantics
- [ ] Replace the template post with the first blog by Maggie

## ⚠️ Known issues

N/A

## 🚫 Blocked by

N/A

## 🐾 Next steps

- Implement a blog index (and updates to navigation) 

## 🔍 What does this change?

- Implement a new `/blog/:slug` route rendering MDX pages, supporting the use of next images for the hero image, author image, and in the post. 

### 📜 Does this require a change to the docs?

No

We may need some internal docs for which variables / MDX components are available for blog posts

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1201959586244685/1201694916711104/f) _(internal)_

## 🛡 What tests cover this?

None

## ❓ How to test this?

Open `/blog/test` (or `/blog/whatever-slug-for-maggie's-post`). 

## 📹 Demo

localhost_3000_blog_test (3)

### CODE REVIEW

**Comment by MaggieAppleton** [comment]
This looks great to me ✨

**Comment by nonparibus** [comment]
Subject to (a) social metadata inclusion and (b) substitution of dummy post with @MaggieAppleton's Block Protocol block design guidelines blog post (which will be our first hash.dev/blog post) this is good to merge.

Code block C&P, sidenotes and job listings can be ticketized and addressed in follow-up. Thanks, @nathggns!

**We want this live alongside the blog homepage at the absolute latest by Friday 22nd April.**

**Comment by nonparibus** [comment]
@MaggieAppleton @nathggns Please ping me when the blog post/copy is ready, and loaded into the page, for review. Thanks!

**Comment by nathggns** [comment]
Going to make one pull request with the whole blog in, so going to close this.

**Pull request closed without merging**
