### PR TITLE
Deprecate `IntoReport::report` in favor of `IntoReport::into_report`

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

`report()` could be misleading because of two reasons: 
- It's not returning a `Report` based on the current Result but consuming it
- There is `report()` on the `Termination` trait defined in std (which also leads to annoying auto-import issues in IDEs)

## 🔍 What does this change?

- Add `IntoReport::into_report`
- Deprecate `IntoReport::report` in favor of `IntoReport::into_report`

### CODE REVIEW

**Review by Alfred-Mountfield — COMMENTED** [review]
We wanted to keep breaking-changes to a minimum, but I'm guessing this is going to be released in the same version as #697 which needs breaking changes anyway? If so then I'm good with this, let me know and I'll approve

**Comment by TimDiekmann** [comment]
Yes, I expect it to be the same release. Also, it's currently only deprecated so that the users code won't break.

**Review by Alfred-Mountfield — COMMENTED** [review]
I appreciate we usually want to deprecate first and leave it for a few versions, but perhaps we want to _remove_ it now _**because**_ we're already forcing a major version?

**Comment by Alfred-Mountfield** [comment]
I hadn't thought about the fact that the breaking change applied to nightly only (and only if used). I agree, let's mark as deprecated for a few versions then 👍

**Review by Alfred-Mountfield — APPROVED** [review]

**Pull request merged**
