### PR TITLE
GEN-72: Fix clippy not working in CI

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

The CI does not run all clippy lints. This is bad.

## 🔍 What does this change?

For some reason, `[target.cfg(all())]` is not used in CI so as a workaround, the content is exported to `RUSTFLAGS`. To make sure everything is still well tested, the toolchain for all crates were bumped and errors are solved.

### 🚢 Has this modified a publishable library?

This PR:

- [x] does not modify any publishable blocks or libraries, or modifications do not need publishing

### 📜 Does this require a change to the docs?

The changes in this PR:

- [x] are internal and do not require a docs change

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

- [x] do not affect the execution graph

### CODE REVIEW

**Review by indietyp — APPROVED** [review]

**Comment by indietyp** [comment]
Has been a wild ride^^

**Comment by TimDiekmann** [comment]
Oh yes, and I'd love to know what's the underlying issue. Maybe because we explicitly set `RUSTFLAGS`?

**Comment by TimDiekmann** [comment]
Actually, yes, that's the issue. Good we talked about it 😂 
Will figure this out in another PR.

**Comment by TimDiekmann** [comment]
The `RUSTFLAGS` environment variable overwrites the flags specified in the config. See [the relevant section](https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags):

> There are four mutually exclusive sources of extra flags. They are checked in order, with the first one being used:
> 1. `CARGO_ENCODED_RUSTFLAGS` environment variable.
> 2. `RUSTFLAGS` environment variable.
> 3. All matching `target.<triple>.rustflags` and `target.<cfg>.rustflags` config entries joined together.
> 4. `build.rustflags` config value.

**Pull request merged**
