### PR TITLE
use EditableField & add wrapperSx prop to it

### PR DESCRIPTION
**Pull request by yusufkinatas**
## 🌟 What is the purpose of this PR?

This PR replaces custom title components as Kanban Board & Table block with  EditableField

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203801045329780/1204256944614937/f) _(internal)_

## 🔍 What does this change?

- Add `wrapperSx` prop to `EditableField`
- Remove few unused files 

## 🚀 Has this modified a publishable library?

This PR:

- [x] modifies an **npm**-publishable library and **I have added a changeset file(s)**
- [ ] modifies a **Cargo**-publishable library and **I have amended the version**
- [ ] modifies a **Cargo**-publishable library, but **it is not yet ready to publish**
- [x] modifies a **block** that will need publishing via GitHub action once merged
- [ ] does not modify any publishable blocks or libraries
- [ ] I am unsure / need advice

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Test titles of `Kanban` & `Table` blocks

### CODE REVIEW

**Review by luisbettencourt — APPROVED** [review]

**Review by luisbettencourt — CHANGES_REQUESTED** [review]
You need to add a minor patch for both blocks in the changeset, right?

**Comment by yusufkinatas** [comment]
@luisbettencourt Afaik no, because we're publishing Tables manually.

**Comment by CiaranMn** [comment]
> We don't use changesets for blocks as far as I'm aware.

@luisbettencourt @yusufkinatas this is correct. Block publishing is not handled via changesets (it might be in future)

**Review by luisbettencourt — APPROVED** [review]
My bad, got it mixed up!

**Pull request merged**
