### PR TITLE
Revert "H-167: `hash-graph-types`: Add marker classes and unify interface"

### PR DESCRIPTION
**Pull request by TimDiekmann**
Reverts hashintel/hash#2776

H-167 sadly introduced a few issues with the generated schema, so the generated schema is wrong. Until this is fixed this will revert the change.

To demonstrate, this is a before/after example for `https://blockprotocol.org/@examples/types/entity-type/person/v/1`.

The new schema looks like this:
```json
{
  "additionalProperties": false,
  "properties": {
    "https://blockprotocol.org/@examples/types/property-type/e-mail/": {
      "$id": "https://blockprotocol.org/@examples/types/property-type/e-mail/v/1",
      "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
      "allOf": [
        {
          "$id": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1",
          "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
          "allOf": [
            {
              "title": "https_blockprotocol_org_blockprotocol_types_data_type_text_v_1",
              "type": "string"
            }
          ],
          "description": "An ordered sequence of characters",
          "kind": "dataType",
          "title": "Text"
        }
      ],
      "default": null,
      "description": "An e-mail address.",
      "kind": "propertyType",
      "title": "E-Mail"
    },
    "https://blockprotocol.org/@blockprotocol/types/property-type/name/": {
      "$id": "https://blockprotocol.org/@blockprotocol/types/property-type/name/v/1",
      "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
      "allOf": [
        {
          "$id": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1",
          "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
          "allOf": [
            {
              "title": "https_blockprotocol_org_blockprotocol_types_data_type_text_v_1",
              "type": "string"
            }
          ],
          "description": "An ordered sequence of characters",
          "kind": "dataType",
          "title": "Text"
        }
      ],
      "description": "A word or set of words by which something is known, addressed, or referred to.",
      "kind": "propertyType",
      "title": "Name"
    }
  },
  "required": [
    "https://blockprotocol.org/@blockprotocol/types/property-type/name/"
  ],
  "title": "https_blockprotocol_org_examples_types_entity_type_person_v_1",
  "type": "object"
}
```

whereas the following schema was generated previously:

```json
{
  "$id": "https://blockprotocol.org/@examples/types/entity-type/person/v/1",
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
  "additionalProperties": false,
  "description": "An extremely simplified representation of a person or human being.",
  "kind": "entityType",
  "properties": {
    "https://blockprotocol.org/@examples/types/property-type/e-mail/": {
      "$id": "https://blockprotocol.org/@examples/types/property-type/e-mail/v/1",
      "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
      "allOf": [
        {
          "$id": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1",
          "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
          "description": "An ordered sequence of characters",
          "kind": "dataType",
          "title": "Text",
          "type": "string"
        }
      ],
      "description": "An e-mail address.",
      "kind": "propertyType",
      "title": "E-Mail"
    },
    "https://blockprotocol.org/@blockprotocol/types/property-type/name/": {
      "$id": "https://blockprotocol.org/@blockprotocol/types/property-type/name/v/1",
      "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
      "allOf": [
        {
          "$id": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1",
          "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
          "description": "An ordered sequence of characters",
          "kind": "dataType",
          "title": "Text",
          "type": "string"
        }
      ],
      "description": "A word or set of words by which something is known, addressed, or referred to.",
      "kind": "propertyType",
      "title": "Name"
    }
  },
  "required": [
    "https://blockprotocol.org/@blockprotocol/types/property-type/name/"
  ],
  "title": "Person",
  "type": "object"
}
```

Most notably is that `default` is set to `null` for non-required types and `title` is wrong. also, an additional `allOf` is inserted for properties and all top-level "custom" properties (like `$id` and `$schema`) are missing.

### CODE REVIEW

**Comment by indietyp** [comment]
We can revert the changes for sure, but I am a bit hesitant to do so. I've been trying to reproduce the issue for over an hour now and could not do so.

For reference my output looks like this:

```json
{
    '$defs': {
        'https_blockprotocol_org_blockprotocol_types_data_type_text_v_1': {
            '$id': 'https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1',
            '$schema': 'https://blockprotocol.org/types/modules/graph/0.3/schema/data-type',
            'description': 'An ordered sequence of characters',
            'kind': 'dataType',
            'title': 'Text',
            'type': 'string',
        },
        'https_blockprotocol_org_blockprotocol_types_property_type_name_v_1': {
            '$id': 'https://blockprotocol.org/@blockprotocol/types/property-type/name/v/1',
            '$schema': 'https://blockprotocol.org/types/modules/graph/0.3/schema/property-type',
            'allOf': [
                {
                    '$ref': '#/$defs/https_blockprotocol_org_blockprotocol_types_data_type_text_v_1',
                },
            ],
            'description': 'A word or set of words by which something is known, addressed, or referred to.',
            'kind': 'propertyType',
            'title': 'Name',
        },
        'https_blockprotocol_org_examples_types_property_type_e_mail_v_1': {
            '$id': 'https://blockprotocol.org/@examples/types/property-type/e-mail/v/1',
            '$schema': 'https://blockprotocol.org/types/modules/graph/0.3/schema/property-type',
            'allOf': [
                {
                    '$ref': '#/$defs/https_blockprotocol_org_blockprotocol_types_data_type_text_v_1',
                },
            ],
            'description': 'An e-mail address.',
            'kind': 'propertyType',
            'title': 'E-Mail',
        },
    },
    '$id': 'https://blockprotocol.org/@examples/types/entity-type/person/v/1',
    '$schema': 'https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type',
    'additionalProperties': False,
    'description': 'An extremely simplified representation of a person or human being.',
    'kind': 'entityType',
    'properties': {
        'https://blockprotocol.org/@examples/types/property-type/e-mail/': {
            'allOf': [
                {
                    '$ref': '#/$defs/https_blockprotocol_org_examples_types_property_type_e_mail_v_1',
                },
            ],
            'default': None,
        },
        'https://blockprotocol.org/@blockprotocol/types/property-type/name/': {
            '$ref': '#/$defs/https_blockprotocol_org_blockprotocol_types_property_type_name_v_1',
        },
    },
    'required': [
        'https://blockprotocol.org/@blockprotocol/types/property-type/name/',
    ],
    'title': 'Person',
    'type': 'object',
}
```

**Comment by indietyp** [comment]
I would rather create a new PR that fixes the `default` Problem and adds one more nicety I forgot in the previous PR.

**Comment by indietyp** [comment]
Although considering next week's schedule, I can very much understand that reverting might be of more benefit right now. I'll leave that up to you guys, fine either way! 👍

**Comment by TimDiekmann** [comment]
I think the most concerning problem is that I'm also not able to reproduce it again even though I'm 100% sure I compiled the wheel again and removed `.venv`, especially as I have never seen the output of the OP before. That Poetry has such big problems with dependency resolution is extremely frustrating. I apologize 🫣

I'm fine with anything solving the mismatch but as you mentioned next week this was my main motivation to quickly revert the change to a working state. I'm happy to review any other PR later this day to avoid reverting the linked PR.

**Review by indietyp — APPROVED** [review]
Discussed offline to revert for now 😢

**Pull request merged**
