### PR TITLE
Replace uses of "workspace" with "system"

### PR DESCRIPTION
**Pull request by benwerner01**
## 🌟 What is the purpose of this PR?

Following an [internal discussion](https://hashintel.slack.com/archives/C022217GAHF/p1667823194993749), this PR seeks to replace uses of the word "workspace" with "system" in the HASH App backend.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1202805690238892/1203322851277858/f) _(internal)_

## 🔍 What does this change?

See commits.

## 📜 Does this require a change to the docs?

Not that I'm aware of.

## 🛡 What tests cover this?

None.

## ❓ How to test this?

Check CI linting workflow passes

### CODE REVIEW

**Comment by thehabbos007** [comment]
Seems like `shared/src/types.ts` is missing the replacement :)

**Comment by benwerner01** [comment]
> Seems like shared/src/types.ts is missing the replacement :)

@thehabbos007 good spot, have addressed in https://github.com/hashintel/hash/pull/1350/commits/12f4014047ae4eb58cedc2d637bdcdaadb859b68

**Review by CiaranMn — COMMENTED** [review]
A couple more to replace:
`WorkspaceEntityGQLTypeName` and nearby friends
`generateWorkspacePropertyTypeSchema` and others in `src/model/util.ts`

**Comment by benwerner01** [comment]
> A couple more to replace: `WorkspaceEntityGQLTypeName` and nearby friends `generateWorkspacePropertyTypeSchema` and others in `src/model/util.ts`

@CiaranMn thanks for flagging, have addressed them in https://github.com/hashintel/hash/pull/1350/commits/1ea24dde369db388f71f193f811dbbc5d217e16d

**Review by CiaranMn — APPROVED** [review]
Looks good to me and will save us confusion down the line – thanks @benwerner01

**Pull request merged**
