### PR TITLE
Jump to start of document when pressing Enter in page's title

### PR DESCRIPTION
**Pull request by luisbettencourt**
## 🌟 What is the purpose of this PR?

This PR makes it so the start of a document is focused when pressing the Enter key inside the Title of a page.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203179076056209/1203623179643222/f) _(internal)_

### 🚢 Has this modified a publishable library?

This PR:

- [x] does not modify any publishable blocks or libraries, or modifications do not need publishing 

### 📜 Does this require a change to the docs?

The changes in this PR:

 - [x] is internal and does not require a docs change 

### 🕸️ Does this require a change to the Turbo Graph?

The changes in this PR:

 - [x] does not affect the execution graph

## ⚠️ Known issues

[Paragraph immediately loses focus in Chrome](https://app.asana.com/0/1203179076056209/1204610234070526/f)

## ❓ How to test this?

1.  Navigate to a page;
2.  Focus the title and press Enter;
3. Check that the first block in the document is focused.

### CODE REVIEW

**Comment by luisbettencourt** [comment]
@nonparibus When the first block of a page isn't a text block, it still focus it, but non-text blocks don't really have any visual indicator that they are focused (only for elements focused inside it). Should it skip non-text blocks and focus the first available text block?

**Comment by nonparibus** [comment]
> @nonparibus When the first block of a page isn't a text block it still focus it, but non-text blocks don't really have any visual indicator that they are focused (only for elements focused inside it). Should it skip non-text blocks and focus the first available text block?

No, let's insert a new paragraph block immediately beneath the header in this case (above the existing non-text block as the first element in the page), instead.

**Review by nathggns — DISMISSED** [review]

**Comment by luisbettencourt** [comment]
> > @nonparibus When the first block of a page isn't a text block it still focus it, but non-text blocks don't really have any visual indicator that they are focused (only for elements focused inside it). Should it skip non-text blocks and focus the first available text block?
> 
> No, let's insert a new paragraph block immediately beneath the header in this case (above the existing non-text block as the first element in the page), instead.

This only applies when hitting Enter, not when pressing Arrow Down, right?

**Comment by nonparibus** [comment]
@luisbettencourt Yes. When pressing the down arrow key the block beneath should be inserted into (or selected/highlighted if it is non-text).

**Review by nathggns — DISMISSED** [review]
linting needs to be addressed i think

**Review by nathggns — APPROVED** [review]

**Pull request merged**
