### PR TITLE
Collect Rust Actions to only require one job to pass to enable merging

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

Dynamically collects all GitHub Actions for Rust in one job.

## 🔗 Related links

- [Asana task description](https://app.asana.com/0/1199550852792314/1201600029668233/f)

## 🔍 What does this change?

- Changes the find-job to create a list of packages to test
   - If any file of a rust package is changed, all tests and checks are run (they could depend on each other)
   - rustfmt is only run for the package changed
- Adds a job `enable merging` which can be required be be merged
    - It fails if any ran job failed
    - Otherwise it succeeds

## 🛡 Tests

- ✅ Manual Tests

### CODE REVIEW

**Review by CiaranMn — COMMENTED** [review]
When setting the jobs that are required for a PR to be mergeable, GitHub does not namespace using the workflow - it just uses the job name. In this case, `enable merging`.

So I think we need to include some kind of Rust/engine namespace in the job name, e.g. `engine - enable merging` or `rust - enable merging`, as we'll need another workflow to manage the other packages.

cc @kachkaev for any thoughts - the context is managing required checks in this monorepo, with the `hash` package joining it at the end of the week.

**Comment by TimDiekmann** [comment]
> P.S. I guess you can select the job name and see which it is, and if we have multiple enable merging they actually point to different things - so maybe we can live with that. But probably avoids confusion if we include the namespace in the job name.

Actually I'd prefer it that way anyway, because the **Required** flag has only be set once but looking at the pull request and reading "Rust / enable merging (pull_request)" seems very intuitive. If we would name it e.g. `enable merging (rust)` or similar, it would look weird, but at least it wouldn't be confusing. Currently, the action scans for _every_ Rust crate (looking up `Cargo.toml`) and use that subdirectory to determine if an action should run. Iff we'd add Rust crates for other things but the engine, `enable merging (engine)` would be incorrect.

**Comment by TimDiekmann** [comment]
Don't help with the concern, but I like "Rust / merging enabled" even more.

**Comment by Alfred-Mountfield** [comment]
I think we might need to have a wider discussion around what level of control we wish to have over CI checks. It seems at the moment there is a lack of clarity on if we want to do it by language **(1.)** or by project **(2.)**. Some very quick (and incomplete) thoughts off the top of my head:

1. Is generic across all packages so if we add more than `hash` and `engine` in the future we won't have to create new CI configs for them if they use an existing language. Also could ensure consistency for styling and such. I think it creates a lot of problems though.
2. Allows us to have bespoke configurations per project, `engine` JS components for example don't need to worry about satisfying the `hash` CI configurations. This also allows us to put more expectations into the CI, about the existence of certain package managers or linting configurations, etc. 

Probably worth discussing off Github and then posting a conclusion here

**Comment by TimDiekmann** [comment]
It may be worth adding a `.github/LANG/config.json` and parse them in the setup job as we proceed. That way, we would only need one config/CI file, which also trims the checks listed at every PR, but if a more specific config is needed, it could just be added to the config. For Rust I could imagine a config file like
```json
{
    "package/engine": {
        "test": {
            "flags": ["--all-features"]
        },
        "clippy": {
            "flags": ["--all-features", "--no-default--features --features "build_nng"]
        },
    },
    "package/engine/lib/error": {
        "test": {
            "flags": ["--all-features", "--no-default--features"]
        },
        "clippy": {
            "flags": ["--all-features", "--no-default--features"]
        },
        "miri" {
            "enabled": true
        }
    },
    "package/whatever": {
        "clippy": {
            "required": false
        }
    }
}
```

**Comment by TimDiekmann** [comment]
Currently, "merging enabled" is skipped if the CI fails. Do we want it to fail? (Little bit more effort to implement, about 10 minutes)

**Review by CiaranMn — APPROVED** [review]
Thanks Tim - agreed that it's fine to just keep the job name without any engine/rust qualifier in it, as it only affects picking the required check.

Let me know when you're ready to merge and I can update the required checks to make this mergeable.

**Comment by CiaranMn** [comment]
> Currently, "merging enabled" is skipped if the CI fails. Do we want it to fail? (Little bit more effort to implement, about 10 minutes)

@TimDiekmann missed this comment - let's fail it, otherwise it's just 'waiting for status to be reported' indefinitely in the list.

**Comment by TimDiekmann** [comment]
The PR is ready to be merged.

**Pull request merged**
