### PR TITLE
Remove `apps/hashdotai/resources` folder

### PR DESCRIPTION
**Pull request by nonparibus**
## 🌟 What is the purpose of this PR?

Moves the directory's contents up a level and ensures both the `hashdotai` and `hashdotdev` sites are properly licensed.

We should make sure that Algolia indexing still behaves as expected.

Should be merged in conjunction with [internal#3443](https://github.com/hashintel/internal/pull/3443).

### CODE REVIEW

**Review by kachkaev — COMMENTED** [review]
Let me push something to fix CI

**Comment by nonparibus** [comment]
D'oh, thank you (re: https://github.com/hashintel/hash/pull/1847/commits/ee4af7284b89d493ba7fd37ff82139735b764ae9)

**Review by kachkaev — APPROVED** [review]

**Comment by nonparibus** [comment]
@kachkaev Was `.gitignore` intentionally omitted from https://github.com/hashintel/hash/pull/1847/commits/f4eedd818ebe9661d93fbbb45ec39b3329e10922?

**Comment by kachkaev** [comment]
> Was `.gitignore` intentionally omitted from https://github.com/hashintel/hash/pull/1847/commits/f4eedd818ebe9661d93fbbb45ec39b3329e10922?

Yes. We want to keep `LICENSE.md` and `LICENSE-*.md` files tracked, but not linted. They are added to a section called `Shared between linters`

**Pull request merged**
