### PR TITLE
Replace simple Rust behaviors with JS for example simulation to be tested 

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

We currently don't support Rust behaviors yet, in order to test a few more simulations, we should replace very simple Rust behaviors with JS: `age.rs` and `move_in_direction.rs`

Doing this enables two additional examples to be run and discovered two new bugs!

## 🚫 Blocked by

- [x] #559
- [x] hashdeps/shared_memory-rs#38
- [ ] [Investigate memory leak](https://app.asana.com/0/1199548034582004/1202479511750422/f) (_internal_)

## 🐾 Next steps

Investigate the new bugs and fix them

## 🔍 What does this change?

Replaces the `age.rs` and `move_in_direction.rs` with simple JavaScript behaviors to be tested at examples.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1201893074552404/1201832146336433/f) _(internal)_

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203358502199039

### CODE REVIEW

**Review by Alfred-Mountfield — APPROVED** [review]

**Review by Alfred-Mountfield — APPROVED** [review]

**Comment by TimDiekmann** [comment]
The PR fails at the CI with an error, which is very very likely because arrow-rs have different expectations than JavaScript's arrow implementation. I marked this as blocked by [Move to Arrow2](https://app.asana.com/0/1199548034582004/1201999214936733/f) (_internal_).

**Review by leudz — DISMISSED** [review]

**Review by Alfred-Mountfield — APPROVED** [review]
Noice 🚀 

Perhaps we want to make an asana task (or add comments) saying to revert this and swap back to .rs behaviours when the Rust runner is implemented

Thanks for making tasks to track the new bugs

**Comment by TimDiekmann** [comment]
Weird, the `test` job is failing while the `bench` job is passing 🤔

**Comment by TimDiekmann** [comment]
I triggered a new run. Maybe it was a very unlucky spurious failure (somehow the test was terminated by SIGKILL). I will investigate this later.

**Comment by TimDiekmann** [comment]
It appears that we have a memory leak in hEngine and this is accumulating when running multiple tests. 
This PR is ready to be merged but my worry is, that we will have some spurious failures due to the leak when running the CI on Pull Requests. As I don't see many benefits in merging this PR right away, I will hold back merging until the leak is fixed.

[Asana Task](https://app.asana.com/0/1199548034582004/1202479511750422/f) (_internal_)

**Comment by nonparibus** [comment]
To revisit as part of [this task](https://app.asana.com/0/1199548034582004/1203358502199033/f) (internal link)

**Pull request closed without merging**
