### PR TITLE
Introduce Changesets

### PR DESCRIPTION
**Pull request by kachkaev**
## 🌟 What is the purpose of this PR?

This PR introduces [Changesets](https://github.com/changesets/changesets) to the HASH monorepo, which allows us to publish npm packages using GitHub Actions. The setup is generally copied from [blockprotocol/blockprotocol](https://github.com/blockprotocol/blockprotocol) with a couple of small amendments. Amendments include references to the right repo as well as updates to patches to install the latest available versions. The [patch](https://github.com/blockprotocol/blockprotocol/blob/3f386e59638f25deef501d71263e47526704953b/patches/%40changesets%2Bapply-release-plan%2B6.1.2.patch) for `@changesets/apply-release-plan` is not included as it is specific to block templates.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203543026679373/1203767287750347/f) _(internal)_

## 🐾 Next steps

- Update `@changesets/*` versions in BP repo  
   https://github.com/blockprotocol/blockprotocol/pull/908
- Configure `MACHINE_USER_TOKEN` and `NPM_TOKEN` in GitHub secrets (@CiaranMn)

## 🛡 What tests cover this?

- Linting

## ❓ How to test this?

Try releasing a package once the PR is merged (we can’t do much testing

### CODE REVIEW

**Review by CiaranMn — APPROVED** [review]

**Comment by nonparibus** [comment]
^ This looks like CI flakiness to me. Also impacted https://github.com/hashintel/hash/pull/1937

**Pull request merged**
