### PR TITLE
Use `tracing` instead of `log`

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

Replace `log` with a structured logging library `tracing`

## 🔗 Related links

- [Asana task description](https://app.asana.com/0/1199550852792314/1201612388082320/f)

## 🔍 What does this change?

Replaces the `log` crate with `tracing` crate. The macros are backwards compatible (even though `tracing`s are more powerful). They inspect the current span and add it to the log entry: https://github.com/hashintel/hash/blob/fc161e9fb6bf64ba31aa91b9d5f792c460136834/packages/engine/bin/cli/src/experiment.rs#L55-L61
Spans also enables us to print `SpanTraces`.

## 🛡 Tests

- ✅ Manual Tests

## 📹 Demo

```
     0.013644156s  INFO hash_engine::utils: Setting `ENGINE_START_TIMEOUT=2`
    at src/utils.rs:35
    in cli::experiment::run_experiment_with_manifest with , project_name: "sugarscape", experiment_id: "single_run-85adf6"

     0.056424725s  INFO hash_engine: HASH Engine process started for experiment single_run-85adf6
    at bin/server/src/main.rs:11

     0.154515008s  INFO hash_engine::utils: Setting `ENGINE_WAIT_TIMEOUT=60`
    at src/utils.rs:35
    in cli::experiment::run_experiment_with_manifest with , project_name: "sugarscape", experiment_id: "single_run-85adf6"

     0.509995201s ERROR cli::experiment: Got error: "Worker error: JavaScript runner error: Datastore: Shared memory error: `/dev/shm`is out of memory"
    at bin/cli/src/experiment.rs:160
    in cli::experiment::run_experiment_with_manifest with , project_name: "sugarscape", experiment_id: "single_run-85adf6"
```

### CODE REVIEW

**Comment by Alfred-Mountfield** [comment]
Can you clarify the options we have when this is merged? 
By that I mean things like features we can compile with, or environment variables we can set, etc.

**Comment by TimDiekmann** [comment]
[`tracing`](https://docs.rs/tracing) can be used as a drop-in replacement for `log`.
> `tracing` is a framework for instrumenting Rust programs to collect structured, event-based diagnostic information.

I added a few configurations that the output is actually more readable but the functionality we currently have remains. https://github.com/hashintel/hash/blob/fc161e9fb6bf64ba31aa91b9d5f792c460136834/packages/engine/src/utils.rs#L20 ensures, that we can use the `RUSTLOG` environment as before.

---

Generally, `tracing` has more options to create [events](https://docs.rs/tracing/latest/tracing/#events) (`info!`, `error!` etc.). Currently, we only use the macros like before, so only adding a string and rarely we set the target manually. With `tracing` it's also possible to [add arbitrary values](https://docs.rs/tracing/latest/tracing/#recording-fields).

The key point of `tracing`, however are [spans](https://docs.rs/tracing/latest/tracing/#spans):
> To record the flow of execution through a program, `tracing` introduces the concept of [spans](https://docs.rs/tracing/latest/tracing/span/index.html). Unlike a log line that represents _a moment in time_, a span represents a _period of time_ with a beginning and an end. When a program begins executing in a context or performing a unit of work, it _enters_ that context’s span, and when it stops executing in that context, it _exits_ the span. The span in which a thread is currently executing is referred to as that thread’s _current_ span.

Spans are added to events and can be captured by `SpanTrace` when generating errors. They can be added manually, or with an `#[instrument]` attribute like https://github.com/hashintel/hash/blob/fc161e9fb6bf64ba31aa91b9d5f792c460136834/packages/engine/bin/cli/src/experiment.rs#L55

I only added the above line as example, I expect more instrumentation statements to be added in the future.

The third concept of `tracing` are [subscribers](https://docs.rs/tracing/latest/tracing/#subscribers), which are using the generated events or spans:
> As `Span`s and `Event`s occur, they are recorded or aggregated by implementations of the [`Subscriber`](https://docs.rs/tracing/latest/tracing/trait.Subscriber.html) trait. `Subscriber`s are notified when an `Event` takes place and when a `Span` is entered or exited.

This is how the logging output and `SpanTrace`s are generated. It's easily possible to add multiple subscribers. My example only uses one subscriber to generate the `SpanTrace`s and one subscriber to output the events to `stdout`.

**Comment by Alfred-Mountfield** [comment]
Appreciate the detail! Could you also roughly comment a bit on the (estimated, while we're lacking proper metrics) performance considerations? Interested in both the configuration you've submitted in the PR and things we might enable through env-vars, features, etc.

Appreciate you might not have any numbers to give but even a rough high-level conversation about performance with the things I mentioned, and with the macro on functions, would be good.

**Comment by TimDiekmann** [comment]
I don't expect to have a major performance impact - neither a regression nor an improvement - from using this crate. As you said, I don't have any numbers or such, but some things why I think so:
- I think both crates are optimized more or less well. `log` (and `env_log`) was almost always there and is used in very many crates. `tracing` itself is [used in the rust compiler](https://github.com/rust-lang/rust/blob/master/compiler/rustc_log/Cargo.toml), so we only have to compare it feature wise.
- both crates only pay for what they use. `EnvFilter` from `tracing` is more or less equal to `env_log`. `env_log` implements `Logger` which pretty much acts as a `Subscriber` for `tracing. I expect both crates to be more or less equal.
- I haven't looked deeply into span generation, but somehow, values are stored which can be printed after leaving the context so I assume that `Clone` is involved here in any kind. Surely, this will impact performance if you'd instrument every function, but as long as we don't do it in the hot path (logging in the hotpath is dumb in any case), we should be fine. E.g. adding the experimental/simulation id on every new experiment/simulation will not impact performance at all.

To conclude: As long as we don't go crazy with spans and values in logs, we are fine.

**Review by Alfred-Mountfield — APPROVED** [review]

**Comment by Alfred-Mountfield** [comment]
Your reasoning holds up to me too :) approved

**Pull request merged**
