### PR TITLE
Add TODOs for potentially unused code

### PR DESCRIPTION
**Pull request by TimDiekmann**
## 🌟 What is the purpose of this PR?

While moving to builders for arrow I noticed a lot of unused code in the datastore module. This PRs adds TODOs all over the code base, wherever code is unused.

## 🐾 Next steps

Triage TODOs on remove the unused code

### CODE REVIEW

**Review by Alfred-Mountfield — COMMENTED** [review]
First of all, thank you for noting all of these down!
Secondly, handling these is going to be a little tough. 

My initial thought was if it's unused delete it, and if we end up needing it again we can re-add it. I still feel like that's the general approach we should take, but it gets problematic. 

At the very least I think we should wait for the Python runner to be included before deleting these because it's possible some of them are necessary. After that we should probably actually go through this PR slowly and see which ones are because of bugs or mistakes in our design, I've noticed one or two that can't just be safely deleted.

**Review by Alfred-Mountfield — COMMENTED** [review]
I guess we could just commit all of these TODOs and have a follow-up task where we just look for the TODOs in the code-base and triage as you say. I was thinking we should triage as part of the PR review but due to my suggestion that we should delay until Python, etc. let's commit. 

To be more consistent with the style of 'special' TODOs we've been creating, perhaps we should change this to `TODO: UNUSED - Needing triage` or something

**Comment by TimDiekmann** [comment]
> At the very least I think we should wait for the Python runner to be included before deleting these because it's possible some of them are necessary.

I tried to not touch any code used by Python, but I agree, that those shouldn't be removed **now**.

> I guess we could just commit all of these TODOs and have a follow-up task.

Yes, that was my proposed way. When this PR got approved I'd add a follow-up task (as in _Next steps_).

> To be more consistent with the style of 'special' TODOs we've been creating, perhaps we should change this to TODO: UNUSED - Needing triage or something

Good point, I changed the comments accordenly.

**Review by Alfred-Mountfield — APPROVED** [review]

**Comment by TimDiekmann** [comment]
[Follow up task](https://app.asana.com/0/1199548034582004/1201892789355293/f) (_internal_)

**Pull request merged**
